### ISSUE TITLE
Traductions

### ISSUE THREAD

**Issue by Seres67** [MicrosoftDocs/cpp-docs.fr-fr#10]
Les traductions sont littérales et donc "try" et "throw" deviennent "essayez" et "lever" (ce qui n'a aucun sens).

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 30a1d03d-a2f4-0b09-63d3-9ef0798d6bf9
* Version Independent ID: 6f1fbb61-074c-d65c-4a1d-ed97687ffff6
* Content: [Instructions try, throw et catch (C++)](https://docs.microsoft.com/fr-fr/cpp/cpp/try-throw-and-catch-statements-cpp?view=vs-2019#feedback)
* Content Source: [docs/cpp/try-throw-and-catch-statements-cpp.md](https://github.com/MicrosoftDocs/cpp-docs.fr-fr/blob/live/docs/cpp/try-throw-and-catch-statements-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by srvbpigh** [comment]
Hello, @Seres67
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Bonjour @Seres67

Merci pour votre feedback. La page en question a été traduite automatiquement, ce qui ne permet pas toujours une bonne compréhension. Nous avons récemment ajouté l’option « Lire en anglais » (sur la droite) qui permet de lire la version anglaise sans avoir à modifier les paramètres de langue. 

Cordialement, 

L’équipe Microsoft DOCS International
