### ISSUE TITLE
cplex 12.4 et visual studio 2010 c++

### ISSUE THREAD

**Issue by saberbenzina** [MicrosoftDocs/cpp-docs.fr-fr#13]
[Tapez vos commentaires ici]

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 8082c1c9-1085-fdd9-0fb3-1b6b1b2aa07b
* Version Independent ID: 9acfdef6-55fa-f5b1-15db-c36a44f9cac1
* Content: [Nouveautés de Visual C++ entre 2003 et 2015](https://docs.microsoft.com/fr-fr/cpp/porting/visual-cpp-what-s-new-2003-through-2015?view=vs-2019)
* Content Source: [docs/porting/visual-cpp-what-s-new-2003-through-2015.md](https://github.com/MicrosoftDocs/cpp-docs.fr-fr/blob/live/docs/porting/visual-cpp-what-s-new-2003-through-2015.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by srvbpigh** [comment]
Hello, @saberbenzina
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
empty
