### ISSUE TITLE
cplex

### ISSUE THREAD

**Issue by saberbenzina** [MicrosoftDocs/cpp-docs.fr-fr#14]
[Tapez vos commentaires ici]

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 8592c227-2f48-9265-14a3-11b1a52fe1d3
* Version Independent ID: 204e8283-834c-0317-b212-9d2fb25b879f
* Content: [Meilleures pratiques de sécurité pour C++](https://docs.microsoft.com/fr-fr/cpp/security/security-best-practices-for-cpp?view=vs-2019)
* Content Source: [docs/security/security-best-practices-for-cpp.md](https://github.com/MicrosoftDocs/cpp-docs.fr-fr/blob/live/docs/security/security-best-practices-for-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-windows**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by srvbpigh** [comment]
Hello, @saberbenzina
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
empty
