### ISSUE TITLE
[translation] new ne devrait pas être traduit.

### ISSUE THREAD

**Issue by Tyrben** [MicrosoftDocs/cpp-docs.fr-fr#19]
La commande new[] est traduite dans le tableau par nouveau[].
C'est une erreur. Il ne faut pas traduire les mots clé du language.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: cc6b306c-010a-3cd1-30cf-cb63da25491a
* Version Independent ID: 3cdd3c4e-7d12-a9bd-d2b9-71307d453c72
* Content: [Allocation de mémoire](https://docs.microsoft.com/fr-fr/cpp/c-runtime-library/memory-allocation?view=msvc-160)
* Content Source: [docs/c-runtime-library/memory-allocation.md](https://github.com/MicrosoftDocs/cpp-docs.fr-fr/blob/live/docs/c-runtime-library/memory-allocation.md)
* Product: **visual-cpp**
* Technology: **cpp-ucrt**
* GitHub Login: @TylerMSFT
* Microsoft Alias: **twhitney**

**Comment by TylerMSFT** [comment]
@Tyrben. Thank you for pointing out that problem. Fixed. Should be live by Friday, 11/20
