### ISSUE TITLE
solution 2 "error: expected primary-expression ....."

### ISSUE THREAD

**Issue by r2d2r01** [MicrosoftDocs/cpp-docs.fr-fr#20]
[Tapez vos commentaires ici]
If u want to avoid error "error: expected primary-expression before ')' token", prefer "`##__VA_ARGS__`"
R2d2

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 17c9f501-4f24-7f53-90f9-c8375802e73f
* Version Independent ID: 0126e007-877f-f21c-266e-4b1fcce0c102
* Content: [Variadiques, macros](https://docs.microsoft.com/fr-fr/cpp/preprocessor/variadic-macros?view=msvc-160)
* Content Source: [docs/preprocessor/variadic-macros.md](https://github.com/MicrosoftDocs/cpp-docs.fr-fr/blob/live/docs/preprocessor/variadic-macros.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@r2d2r01 
The sample code doesn't reproduce the error. This error doesn't occur unless something unexpected is found before the `)`. The error can occur if there's a type name where a variable was expected, or a stray trailing comma. If the [token-pasting operator](https://docs.microsoft.com/cpp/preprocessor/token-pasting-operator-hash-hash?view=msvc-160) fixes an issue with `__VA_ARGS__`, you almost certainly have a bug. It could be a bug in your macro or in the argument list. You can use the [/P (Preprocess to a file)](https://docs.microsoft.com/cpp/build/reference/p-preprocess-to-a-file.md) command to see what the preprocessor does.
