### ISSUE TITLE
Mot manquant 

### ISSUE THREAD

**Issue by LouisJustinTALLOT** [MicrosoftDocs/cpp-docs.fr-fr#21]
Il manque un mot après type
 ```
Le `__int8` type de données est synonyme de type,
```
---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 3e8861ff-0529-f8ac-5604-0457a6a2945b
* Version Independent ID: 08c1903d-877e-a8b0-6258-2a0d32ca9611
* Content: [Types d'entier dimensionné C](https://docs.microsoft.com/fr-fr/cpp/c-language/c-sized-integer-types?view=msvc-160)
* Content Source: [docs/c-language/c-sized-integer-types.md](https://github.com/MicrosoftDocs/cpp-docs.fr-fr/blob/live/docs/c-language/c-sized-integer-types.md)
* Product: **visual-cpp**
* Technology: **cpp-c-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by corob-msft** [comment]
@JasonCard This looks like the translation has moved a comma from between "**`char`**, **`__int16`**" to in front, so it became ", **`char`** **`__int16`**". Is this human error, or an MT issue?

**Comment by JasonCard** [comment]
@LouisJustinTALLOT Thank you for your feedback.
@corob-msft Yes, unfortunately this translation issue is coming from MT engine. Some translation quality issue is expected with machine translation, but customers can use the "Read in English" toggle to check the original English text for reference.

**Comment by LouisJustinTALLOT** [comment]
> @LouisJustinTALLOT Thank you for your feedback.
You are welcome !
