### ISSUE TITLE
Phrase qui ne veut rien dire

### ISSUE THREAD

**Issue by nesdnuma** [MicrosoftDocs/cpp-docs.fr-fr#7]
Bonjour, la phrase "Par conséquent, votre projet est plus probable continuer à créer lorsque vous mettez à niveau le compilateur." ne veut rien dire. Pouvez-vous corriger? Merci.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 594d91da-63e0-5875-ecd0-9c1f92769e18
* Version Independent ID: 83872f73-4c57-8482-f631-760e20886468
* Content: [Avertissement de ligne de commande D9035](https://docs.microsoft.com/fr-fr/cpp/error-messages/tool-errors/command-line-warning-d9035?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DFR-FR%26k%3Dk(D9035)%26rd%3Dtrue&view=vs-2017#feedback)
* Content Source: [docs/error-messages/tool-errors/command-line-warning-d9035.md](https://github.com/MicrosoftDocs/cpp-docs.fr-fr/blob/live/docs/error-messages/tool-errors/command-line-warning-d9035.md)
* Product: **visual-cpp**
* Technology: **cpp-diagnostics**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by CeciAc** [comment]
Bonjour, @nesdnuma 

Merci pour votre feedback. 

Nous révisons activement vos commentaires et nous vous recontacterons bientôt. 

Cordialement, 
L’équipe Microsoft DOCS International

**Comment by CeciAc** [comment]
Bonjour, @nesdnuma

Merci pour votre feedback. 

Notre équipe linguistique a examiné vos suggestions de traduction et les a acceptées. Nous avons modifié les articles concernés selon vos suggestions et les avons republiés sur les pages https://docs.microsoft.com/fr-fr/cpp/error-messages/tool-errors/command-line-warning-d9035?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev15.query%3FappId%3DDev15IDEF1%26l%3DFR-FR%26k%3Dk(D9035)%26rd%3Dtrue&view=vs-2017#feedback du site Docs.  

Votre contribution à nos articles est grandement appréciée. Nous vous encourageons donc à continuer d’envoyer vos commentaires à Microsoft. 

Cordialement, 
L’équipe Microsoft DOCS International
