### ISSUE TITLE
Wtf ?

### ISSUE THREAD

**Issue by Vyraax** [MicrosoftDocs/cpp-docs.fr-fr#8]
J'ai beau relire la description c'est juste incompréhensible. Les phrases n'ont pas l'air françaises.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 8ffaf708-c487-fd33-077b-81ea64a54610
* Version Independent ID: d90a027c-3cfe-fb0e-8a5e-3fbe358baca2
* Content: [__cdecl](https://docs.microsoft.com/fr-fr/cpp/cpp/cdecl?view=vs-2019#feedback)
* Content Source: [docs/cpp/cdecl.md](https://github.com/MicrosoftDocs/cpp-docs.fr-fr/blob/live/docs/cpp/cdecl.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by srvbpigh** [comment]
Hello, @Vyraax
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Bonjour @Vyraax

Merci pour votre feedback. La page en question a été traduite automatiquement, ce qui ne permet pas toujours une bonne compréhension. Nous avons récemment ajouté l’option « Lire en anglais » (sur la droite) qui permet de lire la version anglaise sans avoir à modifier les paramètres de langue. 

Cordialement, 

L’équipe Microsoft DOCS International
